# Site settings ...
uri: ethergency.co
url: http://ethergency.co
name: EtherGency
title: Studio Ethereum Blockchain - EtherGency
email: contact@ethergency.co
author: n1c0
baseurl: ""
keywords: "blockchain, ethereum, studio blochain, agence blockchain"
description: "Join and build us an ethereum blockchain studio :-)"
social_username: ethergency

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
